export const S = {
  app: {
    fontFamily: "'Quicksand', sans-serif",
    minHeight: "100vh",
    background: "linear-gradient(180deg, #FFF8E7 0%, #FFF1D0 50%, #FDEBD0 100%)",
    color: "#2d3436",
    overflowX: "hidden",
  },
  gc: {
    maxWidth: 480,
    margin: "0 auto",
    padding: "12px 16px 40px",
    minHeight: "100vh",
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
    padding: "8px 0",
  },
  backBtn: {
    background: "rgba(255,255,255,0.8)",
    border: "none",
    borderRadius: 12,
    padding: "13px 14px",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
    color: "#555",
    whiteSpace: "nowrap",
    minHeight: 48,
  },
  scoreTag: {
    background: "rgba(255,255,255,0.8)",
    borderRadius: 12,
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: 16,
    whiteSpace: "nowrap",
  },
  card: {
    background: "white",
    borderRadius: 24,
    padding: "24px 20px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.08)",
  },
  gt: {
    fontFamily: "'Fredoka One', cursive",
    fontSize: 28,
    margin: "8px 0",
    color: "#2d3436",
  },
  prompt: {
    textAlign: "center",
    color: "#888",
    fontSize: 16,
    margin: "0 0 8px",
  },
  bigEmoji: {
    textAlign: "center",
    fontSize: 80,
    margin: "8px 0 12px",
    filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.1))",
  },
  emojiGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    margin: "8px 0 20px",
    minHeight: 50,
    alignItems: "center",
  },
  hintBtn: {
    display: "block",
    margin: "0 auto 12px",
    background: "none",
    border: "2px dashed #ddd",
    borderRadius: 12,
    padding: "13px 16px",
    fontSize: 14,
    cursor: "pointer",
    color: "#aaa",
    fontFamily: "'Quicksand', sans-serif",
    fontWeight: 600,
    minHeight: 48,
  },
  hintTxt: {
    textAlign: "center",
    color: "#aaa",
    fontSize: 14,
    fontStyle: "italic",
    margin: "0 0 12px",
  },
  opts: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: 16,
  },
  optBtn: {
    padding: "16px 20px",
    fontSize: 24,
    fontWeight: 700,
    fontFamily: "'Quicksand', sans-serif",
    border: "3px solid #e8e8e8",
    borderRadius: 16,
    background: "#fafafa",
    cursor: "pointer",
    transition: "all 0.2s",
    letterSpacing: 2,
    color: "#2d3436",
  },
  optOk: {
    borderColor: "#4ECDC4",
    background: "#d4edda",
    transform: "scale(1.03)",
  },
  fbBub: {
    marginTop: 16,
    padding: "12px 18px",
    borderRadius: 14,
    textAlign: "center",
    fontSize: 18,
    fontWeight: 700,
    animation: "popIn 0.3s ease",
  },
  btn: {
    padding: "14px 28px",
    fontSize: 18,
    fontWeight: 700,
    fontFamily: "'Quicksand', sans-serif",
    border: "none",
    borderRadius: 14,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  btnP: {
    background: "linear-gradient(135deg, #FF9F43, #e67e22)",
    color: "white",
    boxShadow: "0 4px 0 #d35400",
  },
};
